# Generated by Django 2.2.18 on 2021-03-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biologia', '0029_auto_20210223_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='estado_conservacion_habitat',
            field=models.IntegerField(blank=True, choices=[(1, 'Impactado'), (2, 'Regular'), (3, 'Bueno'), (4, '-')], default=4, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='periodo_dia',
            field=models.IntegerField(blank=True, choices=[(1, 'Diurno'), (2, 'Tarde'), (3, 'Nocturno'), (4, '-')], default=4, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='temporada_evaluacion',
            field=models.IntegerField(blank=True, choices=[(1, 'Seco'), (2, 'Humedo'), (3, 'Nevado'), (4, '-')], default=4, null=True),
        ),
        migrations.AlterField(
            model_name='bd_integrada_aves_chinalco_seca_2018',
            name='tipo_evaluacion',
            field=models.IntegerField(blank=True, choices=[(1, 'Cuantitativo'), (2, 'Cualitativo'), (3, '-')], default=3, null=True),
        ),
    ]
