# Generated by Django 2.2.18 on 2021-03-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biologia', '0031_auto_20210303_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(blank=True, max_length=255, null=True)),
                ('dato1', models.CharField(blank=True, max_length=255, null=True)),
                ('dato2', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
